// Generated by gencpp from file distributed_pgo/PgoStatus.msg
// DO NOT EDIT!


#ifndef DISTRIBUTED_PGO_MESSAGE_PGOSTATUS_H
#define DISTRIBUTED_PGO_MESSAGE_PGOSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace distributed_pgo
{
template <class ContainerAllocator>
struct PgoStatus_
{
  typedef PgoStatus_<ContainerAllocator> Type;

  PgoStatus_()
    : sender_robot_id(0)
    , is_converged(false)
    , current_grad_norm(0.0)  {
    }
  PgoStatus_(const ContainerAllocator& _alloc)
    : sender_robot_id(0)
    , is_converged(false)
    , current_grad_norm(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _sender_robot_id_type;
  _sender_robot_id_type sender_robot_id;

   typedef uint8_t _is_converged_type;
  _is_converged_type is_converged;

   typedef double _current_grad_norm_type;
  _current_grad_norm_type current_grad_norm;





  typedef boost::shared_ptr< ::distributed_pgo::PgoStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::distributed_pgo::PgoStatus_<ContainerAllocator> const> ConstPtr;

}; // struct PgoStatus_

typedef ::distributed_pgo::PgoStatus_<std::allocator<void> > PgoStatus;

typedef boost::shared_ptr< ::distributed_pgo::PgoStatus > PgoStatusPtr;
typedef boost::shared_ptr< ::distributed_pgo::PgoStatus const> PgoStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::distributed_pgo::PgoStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::distributed_pgo::PgoStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::distributed_pgo::PgoStatus_<ContainerAllocator1> & lhs, const ::distributed_pgo::PgoStatus_<ContainerAllocator2> & rhs)
{
  return lhs.sender_robot_id == rhs.sender_robot_id &&
    lhs.is_converged == rhs.is_converged &&
    lhs.current_grad_norm == rhs.current_grad_norm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::distributed_pgo::PgoStatus_<ContainerAllocator1> & lhs, const ::distributed_pgo::PgoStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace distributed_pgo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::distributed_pgo::PgoStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::distributed_pgo::PgoStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::distributed_pgo::PgoStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::distributed_pgo::PgoStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::distributed_pgo::PgoStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::distributed_pgo::PgoStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::distributed_pgo::PgoStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60f16a25306673f726276922d7211a68";
  }

  static const char* value(const ::distributed_pgo::PgoStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60f16a25306673f7ULL;
  static const uint64_t static_value2 = 0x26276922d7211a68ULL;
};

template<class ContainerAllocator>
struct DataType< ::distributed_pgo::PgoStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "distributed_pgo/PgoStatus";
  }

  static const char* value(const ::distributed_pgo::PgoStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::distributed_pgo::PgoStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 sender_robot_id\n"
"bool is_converged\n"
"float64 current_grad_norm\n"
;
  }

  static const char* value(const ::distributed_pgo::PgoStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::distributed_pgo::PgoStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sender_robot_id);
      stream.next(m.is_converged);
      stream.next(m.current_grad_norm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PgoStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::distributed_pgo::PgoStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::distributed_pgo::PgoStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "sender_robot_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sender_robot_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_converged: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_converged);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "current_grad_norm: ";
    Printer<double>::stream(s, indent + "  ", v.current_grad_norm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISTRIBUTED_PGO_MESSAGE_PGOSTATUS_H
