// Generated by gencpp from file distributed_pgo/PgoUpdate.msg
// DO NOT EDIT!


#ifndef DISTRIBUTED_PGO_MESSAGE_PGOUPDATE_H
#define DISTRIBUTED_PGO_MESSAGE_PGOUPDATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace distributed_pgo
{
template <class ContainerAllocator>
struct PgoUpdate_
{
  typedef PgoUpdate_<ContainerAllocator> Type;

  PgoUpdate_()
    : sender_robot_id(0)
    , local_vertex_index(0)
    , pose_pudq()
    , pose_vec3()  {
      pose_pudq.assign(0.0);

      pose_vec3.assign(0.0);
  }
  PgoUpdate_(const ContainerAllocator& _alloc)
    : sender_robot_id(0)
    , local_vertex_index(0)
    , pose_pudq()
    , pose_vec3()  {
  (void)_alloc;
      pose_pudq.assign(0.0);

      pose_vec3.assign(0.0);
  }



   typedef int32_t _sender_robot_id_type;
  _sender_robot_id_type sender_robot_id;

   typedef int32_t _local_vertex_index_type;
  _local_vertex_index_type local_vertex_index;

   typedef boost::array<double, 4>  _pose_pudq_type;
  _pose_pudq_type pose_pudq;

   typedef boost::array<double, 3>  _pose_vec3_type;
  _pose_vec3_type pose_vec3;





  typedef boost::shared_ptr< ::distributed_pgo::PgoUpdate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::distributed_pgo::PgoUpdate_<ContainerAllocator> const> ConstPtr;

}; // struct PgoUpdate_

typedef ::distributed_pgo::PgoUpdate_<std::allocator<void> > PgoUpdate;

typedef boost::shared_ptr< ::distributed_pgo::PgoUpdate > PgoUpdatePtr;
typedef boost::shared_ptr< ::distributed_pgo::PgoUpdate const> PgoUpdateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::distributed_pgo::PgoUpdate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::distributed_pgo::PgoUpdate_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::distributed_pgo::PgoUpdate_<ContainerAllocator1> & lhs, const ::distributed_pgo::PgoUpdate_<ContainerAllocator2> & rhs)
{
  return lhs.sender_robot_id == rhs.sender_robot_id &&
    lhs.local_vertex_index == rhs.local_vertex_index &&
    lhs.pose_pudq == rhs.pose_pudq &&
    lhs.pose_vec3 == rhs.pose_vec3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::distributed_pgo::PgoUpdate_<ContainerAllocator1> & lhs, const ::distributed_pgo::PgoUpdate_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace distributed_pgo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::distributed_pgo::PgoUpdate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::distributed_pgo::PgoUpdate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::distributed_pgo::PgoUpdate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::distributed_pgo::PgoUpdate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::distributed_pgo::PgoUpdate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::distributed_pgo::PgoUpdate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::distributed_pgo::PgoUpdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bbcafeecfadfbe48488d6fc36fc38955";
  }

  static const char* value(const ::distributed_pgo::PgoUpdate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbbcafeecfadfbe48ULL;
  static const uint64_t static_value2 = 0x488d6fc36fc38955ULL;
};

template<class ContainerAllocator>
struct DataType< ::distributed_pgo::PgoUpdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "distributed_pgo/PgoUpdate";
  }

  static const char* value(const ::distributed_pgo::PgoUpdate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::distributed_pgo::PgoUpdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 sender_robot_id\n"
"int32 local_vertex_index\n"
"float64[4] pose_pudq\n"
"float64[3] pose_vec3\n"
;
  }

  static const char* value(const ::distributed_pgo::PgoUpdate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::distributed_pgo::PgoUpdate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sender_robot_id);
      stream.next(m.local_vertex_index);
      stream.next(m.pose_pudq);
      stream.next(m.pose_vec3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PgoUpdate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::distributed_pgo::PgoUpdate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::distributed_pgo::PgoUpdate_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "sender_robot_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sender_robot_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "local_vertex_index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.local_vertex_index);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose_pudq: ";
    if (v.pose_pudq.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.pose_pudq.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.pose_pudq[i]);
    }
    if (v.pose_pudq.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose_vec3: ";
    if (v.pose_vec3.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.pose_vec3.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.pose_vec3[i]);
    }
    if (v.pose_vec3.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISTRIBUTED_PGO_MESSAGE_PGOUPDATE_H
