# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from distributed_pgo/PgoStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PgoStatus(genpy.Message):
  _md5sum = "60f16a25306673f726276922d7211a68"
  _type = "distributed_pgo/PgoStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 sender_robot_id
bool is_converged
float64 current_grad_norm"""
  __slots__ = ['sender_robot_id','is_converged','current_grad_norm']
  _slot_types = ['int32','bool','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sender_robot_id,is_converged,current_grad_norm

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PgoStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.sender_robot_id is None:
        self.sender_robot_id = 0
      if self.is_converged is None:
        self.is_converged = False
      if self.current_grad_norm is None:
        self.current_grad_norm = 0.
    else:
      self.sender_robot_id = 0
      self.is_converged = False
      self.current_grad_norm = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_iBd().pack(_x.sender_robot_id, _x.is_converged, _x.current_grad_norm))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.sender_robot_id, _x.is_converged, _x.current_grad_norm,) = _get_struct_iBd().unpack(str[start:end])
      self.is_converged = bool(self.is_converged)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_iBd().pack(_x.sender_robot_id, _x.is_converged, _x.current_grad_norm))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.sender_robot_id, _x.is_converged, _x.current_grad_norm,) = _get_struct_iBd().unpack(str[start:end])
      self.is_converged = bool(self.is_converged)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_iBd = None
def _get_struct_iBd():
    global _struct_iBd
    if _struct_iBd is None:
        _struct_iBd = struct.Struct("<iBd")
    return _struct_iBd
